version: "3.8"

services:
  web.app:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
    ports:
      - '3001:80'
      
volumes:
  node_modules:
  dist: